### ISSUE TITLE
Report results on all datasets with L2 and other types of regularization 

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/path2vec#9]

**Comment by akutuzov** [comment]
Hi @m-dorgham 
Are these your results? 
https://docs.google.com/spreadsheets/d/1KjNns16ld3pVUY1K7aA0HH9Lrb1PiKBH7-ZIbWrD9Kc/edit

How exactly did you evaluate your models (what code yo used)?  In the google doc, you report the scores of 0.5007 for static synset selection and 0.5494 for dynamic synset selection (JCN-SemCor).
But when I train a model with the same hyperparameters (L1 regularization, 1 neighbor, vsize 300, bsize 100, lrate 0.001), I get only 0.4885 and 0.5276 correspondingly.

**Comment by m-dorgham** [comment]
Hi @akutuzov 
This sheet is not mine, it's the first time I see it.
My results are written in this sheet
https://docs.google.com/spreadsheets/d/1esXh-eNz76_86PikQe9-FwkeEpMz7Of6rzeiSS6lrD8/edit?usp=sharing

The last results after making the choice of neighbors random is 0.5027, 0.4687 for static and dynamic synset selection respectively for 1 neighbor, and 0.5005, 0.5325 for 3 neighbors.

Please make sure to pull the last code because I made some changes recently.

**Comment by akutuzov** [comment]
So, once again, what code you use to evaluate your models?

**Comment by m-dorgham** [comment]
I use embeddings.py to train the model and evaluation.py to evaluate the model. I used the near50 dataset files as a source of training (jcn-semcor-thresh01-near50.tsv.gz, jcn-brown-thresh01-near50.tsv.gz, lch-thresh15-near50.tsv.gz).

**Comment by akutuzov** [comment]
Confirmed.
